language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: false

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: PHPCS=1

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction
  - if [[ '$PHPCS' != '1' && $TRAVIS_PHP_VERSION = 5.6 ]]; then composer require phpunit/phpunit:4.8.*; fi

script:
  - if [[ '$PHPCS' != '1' && $TRAVIS_PHP_VERSION = 7.* ]]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi
  - if [[ '$PHPCS' != '1' && $TRAVIS_PHP_VERSION != 7.* ]]; then phpunit; fi
  - if [ '$PHPCS' = '1' ]; then ./vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi

notifications:
  email: false

after_success:
- bash <(curl -s https://codecov.io/bash)
